---
title: "sc_RNA_tonsil"
author: "Shruti"
date: "10/10/2022"
output: html_document
---

```{r}
library(dplyr)
library(tidyverse)
library(Seurat)
library(patchwork)
library(ggplot2)
```

```{r}

# Read dataset 
tonsil <- readRDS("~/Desktop/sc-RNASeq/Tonsil.rds")
```

```{r}

# Created weighted gene list

CD68_GC <- read.table("~/Downloads/DE_Allgenes_GC_vs_interfollicular_CD68.txt", header = T)
CD68_GC <- CD68_GC %>% mutate(bon = p.adjust(P.Value, method = "bonferroni"))
CD68_GC <- CD68_GC %>% mutate(weight = -log10(bon))
CD68_GC_up <- CD68_GC %>% dplyr::filter(logFC > 1.5 & bon < 0.05)
CD68_GC_down <- CD68_GC %>% dplyr::filter(logFC < - 1.5 & bon < 0.05)

CD68_DZ <- read.table("~/Downloads/DE_Allgenes_DZ_vs_LZ_CD68.txt", header = T)
#CD68_DZ <- CD68_DZ %>% mutate(bon = p.adjust(P.Value, method = "bonferroni"))
CD68_DZ <- CD68_DZ %>% mutate(weight = -log10(adj.P.Val))
CD68_DZ_up <- CD68_DZ %>% filter(logFC > 0.7)
CD68_DZ_down <- CD68_DZ %>% filter(logFC < - 0.7)

CD3_GC <- read.table("~/Downloads/DE_Allgenes_GC_vs_interfollicular_CD3.txt", header = T)
CD3_GC <- CD3_GC %>% mutate(bon = p.adjust(P.Value, method = "bonferroni"))
CD3_GC <- CD3_GC %>% mutate(weight = -log10(bon))
CD3_GC_up <- CD3_GC %>% filter(logFC > 1.5 & bon < 0.05)
CD3_GC_down <- CD3_GC %>% filter(logFC < - 1.5 & bon < 0.05)

```

```{r}
z <- DoHeatmap(tonsil, features = CD68_GC_up$geni) + NoLegend()
y <- z$data %>% drop_na()
x <- y %>% group_by(Identity) %>% dplyr::select(Feature, Cell, Identity, Expression) %>%
    tidyr::spread(key = Feature, value = Expression)
w <- y %>% dplyr::select(Feature, Cell, Expression) %>%
    tidyr::spread(key = Cell, value = Expression) %>% column_to_rownames("Feature") %>% as.matrix()
w <- as.data.frame(w)
w <- w %>% mutate(Names = rownames(w))
```

```{r}

## Add weights to the genes

CD68_GC_up_final <- CD68_GC_up[rownames(CD68_GC_up) %in% rownames(w),]
i <-  1
j <-  1
for(i in 1: nrow(w)){
  for(j in 1: nrow(CD68_GC_up_final)){
    if(CD68_GC_up_final$geni[j] == w$Names[i]){
      w[i ,1:26844] <- w[i ,1:26844]*CD68_GC_up_final$weight[j]
      print(i);
    }
  }
}
```

```{r}

#GC Score

sum(CD68_GC_up_final$weight)
w_new <- w
w_new <- w_new[,-c(26845)]
w_new[15,] <- colSums(w_new)/sum(CD68_GC_up_final$weight)
w_new <- t(w_new)
w_new <- as.data.frame(w_new)
w_new_final <- w_new[match(rownames(DLBCL@meta.data), rownames(w_new)), ]
DLBCL@meta.data$DLBCL_Score <- w_new_final$`15`
FeaturePlot(tonsil, features = "DLBCL_Score") + scale_colour_gradientn(colours = rev(brewer.pal(n = 11, name = "RdYlBu")))

```

```{r}
#IF Score 

z <- DoHeatmap(tonsil, features = CD68_GC_down$geni) + NoLegend()
y <- z$data %>% drop_na()
x <- y %>% group_by(Identity) %>% dplyr::select(Feature, Cell, Identity, Expression) %>%
    tidyr::spread(key = Feature, value = Expression)
w_1 <- y %>% dplyr::select(Feature, Cell, Expression) %>%
    tidyr::spread(key = Cell, value = Expression) %>% column_to_rownames("Feature") %>% as.matrix()

w_1 <- as.data.frame(w_1)
w_1 <- w_1 %>% mutate(Names = rownames(w_1))


i <-  1
j <-  1
for(i in 1: nrow(w_1)){
  for(j in 1: nrow(CD68_GC_down)){
    if(CD68_GC_down$geni[j] == w_1$Names[i]){
      w_1[i ,1:59742] <- w_1[i ,1:59742]*CD68_GC_down$weight[j]
      print(i);
    }
  }
}

CD68_GC_down_final <- CD68_GC_down[rownames(CD68_GC_down) %in% rownames(w_1),]

sum(CD68_GC_down_final$weight)
w_new <- w_1
w_new <- w_new[,-c(59743)]
w_new[17,] <- colSums(w_new)/sum(CD68_GC_down_final$weight)
w_new <- t(w_new)
w_new <- as.data.frame(w_new)
w_new_final <- w_new[match(rownames(tonsil@meta.data), rownames(w_new)), ]
tonsil@meta.data$GC_Score1 <- w_new_final$`17`
FeaturePlot(tonsil, features = "GC_Score1") + scale_colour_gradientn(colours = rev(brewer.pal(n = 11, name = "RdYlBu")))

```

```{r}

#DZ Score

z_1 <- DoHeatmap(tonsil, features = CD68_DZ_up$geni) + NoLegend()
y_1 <- z_1$data %>% drop_na()
x_1 <- y_1 %>% group_by(Identity) %>% dplyr::select(Feature, Cell, Identity, Expression) %>%
    tidyr::spread(key = Feature, value = Expression)
w_2 <- y_1 %>% dplyr::select(Feature, Cell, Expression) %>%
    tidyr::spread(key = Cell, value = Expression) %>% column_to_rownames("Feature") %>% as.matrix()

w_2 <- as.data.frame(w_2)
w_2 <- w_2 %>% mutate(Names = rownames(w_2))


i <-  1
j <-  1
for(i in 1: nrow(w_2)){
  for(j in 1: nrow(CD68_DZ_up)){
    if(CD68_DZ_up$geni[j] == w_2$Names[i]){
      w_2[i ,1:59742] <- w_2[i ,1:59742]*CD68_DZ_up$weight[j]
      print(i);
    }
  }
}

CD68_DZ_up_final <- CD68_DZ_up[rownames(CD68_DZ_up) %in% rownames(w_2),]
dim(w_2)

sum(CD68_DZ_up_final$weight)
w_new_1 <- w_2
w_new_1 <- w_new_1[,-c(59743)]
w_new_1[35,] <- colSums(w_new_1)/sum(CD68_DZ_up_final$weight)
w_new_1 <- t(w_new_1)
w_new_1 <- as.data.frame(w_new_1)
w_new_final_1 <- w_new_1[match(rownames(tonsil@meta.data), rownames(w_new_1)), ]
tonsil@meta.data$DZ_Score <- w_new_final_1$`35`
FeaturePlot(tonsil, features = "DZ_Score") + scale_colour_gradientn(colours = rev(brewer.pal(n = 11, name = "RdYlBu")))



```



```{r}
#LZ Score

z_1 <- DoHeatmap(tonsil, features = CD68_DZ_down$geni) + NoLegend()
y_1 <- z_1$data %>% drop_na()
x_1 <- y_1 %>% group_by(Identity) %>% dplyr::select(Feature, Cell, Identity, Expression) %>%
    tidyr::spread(key = Feature, value = Expression)
w_2 <- y_1 %>% dplyr::select(Feature, Cell, Expression) %>%
    tidyr::spread(key = Cell, value = Expression) %>% column_to_rownames("Feature") %>% as.matrix()

w_2 <- as.data.frame(w_2)
w_2 <- w_2 %>% mutate(Names = rownames(w_2))


i <-  1
j <-  1
for(i in 1: nrow(w_2)){
  for(j in 1: nrow(CD68_DZ_down)){
    if(CD68_DZ_down$geni[j] == w_2$Names[i]){
      w_2[i ,1:59742] <- w_2[i ,1:59742]*CD68_DZ_down$weight[j]
      print(i);
    }
  }
}

CD68_DZ_down_final <- CD68_DZ_down[rownames(CD68_DZ_down) %in% rownames(w_2),]
dim(w_2)

sum(CD68_DZ_down_final$weight)
w_new_1 <- w_2
w_new_1 <- w_new_1[,-c(59743)]
dim(w_2)
w_new_1[32,] <- colSums(w_new_1)/sum(CD68_DZ_up_final$weight)
w_new_1 <- t(w_new_1)
w_new_1 <- as.data.frame(w_new_1)
w_new_final_1 <- w_new_1[match(rownames(tonsil@meta.data), rownames(w_new_1)), ]
tonsil@meta.data$LZ_Score <- w_new_final_1$`32`
FeaturePlot(tonsil, features = "LZ_Score") + scale_colour_gradientn(colours = rev(brewer.pal(n = 11, name = "RdYlBu")))

```

```{r}
#CD3+ GC

z <- DoHeatmap(tonsil, features = CD3_GC_up$geni) + NoLegend()
y <- z$data %>% drop_na()
x <- y %>% group_by(Identity) %>% dplyr::select(Feature, Cell, Identity, Expression) %>%
    tidyr::spread(key = Feature, value = Expression)
w <- y %>% dplyr::select(Feature, Cell, Expression) %>%
    tidyr::spread(key = Cell, value = Expression) %>% column_to_rownames("Feature") %>% as.matrix()
w <- as.data.frame(w)
w <- w %>% mutate(Names = rownames(w))

CD3_GC_up_final <- CD3_GC_up[rownames(CD3_GC_up) %in% rownames(w),]
i <-  1
j <-  1
for(i in 1: nrow(w)){
  for(j in 1: nrow(CD3_GC_up_final)){
    if(CD3_GC_up_final$geni[j] == w$Names[i]){
      w[i ,1:59742] <- w[i ,1:59742]*CD3_GC_up_final$weight[j]
      print(i);
    }
  }
}

sum(CD3_GC_up_final$weight)
w_new <- w
w_new <- w_new[,-c(59743)]
dim(w_new)


w_new[29,] <- colSums(w_new)/sum(CD3_GC_up_final$weight)
w_new <- t(w_new)
w_new <- as.data.frame(w_new)
w_new_final <- w_new[match(rownames(tonsil@meta.data), rownames(w_new)), ]
tonsil@meta.data$CD3_GC_Score <- w_new_final$`29`
FeaturePlot(tonsil, features = "CD3_GC_Score") + scale_colour_gradientn(colours = rev(brewer.pal(n = 11, name = "RdYlBu")))

```

```{r}
#CD3 IF Score

z <- DoHeatmap(tonsil, features = CD3_GC_down$geni) + NoLegend()
y <- z$data %>% drop_na()
x <- y %>% group_by(Identity) %>% dplyr::select(Feature, Cell, Identity, Expression) %>%
    tidyr::spread(key = Feature, value = Expression)
w_1 <- y %>% dplyr::select(Feature, Cell, Expression) %>%
    tidyr::spread(key = Cell, value = Expression) %>% column_to_rownames("Feature") %>% as.matrix()

w_1 <- as.data.frame(w_1)
w_1 <- w_1 %>% mutate(Names = rownames(w_1))


i <-  1
j <-  1
for(i in 1: nrow(w_1)){
  for(j in 1: nrow(CD3_GC_down)){
    if(CD3_GC_down$geni[j] == w_1$Names[i]){
      w_1[i ,1:59742] <- w_1[i ,1:59742]*CD3_GC_down$weight[j]
      print(i);
    }
  }
}

CD3_GC_down_final <- CD3_GC_down[rownames(CD3_GC_down) %in% rownames(w_1),]

sum(CD3_GC_down_final$weight)
w_new <- w_1
w_new <- w_new[,-c(59743)]


w_new[6,] <- colSums(w_new)/sum(CD68_GC_down_final$weight)
w_new <- t(w_new)
w_new <- as.data.frame(w_new)
w_new_final <- w_new[match(rownames(tonsil@meta.data), rownames(w_new)), ]
tonsil@meta.data$CD3_IF_Score <- w_new_final$`6`
FeaturePlot(tonsil, features = "CD3_IF_Score") + scale_colour_gradientn(colours = rev(brewer.pal(n = 11, name = "RdYlBu")))

```

```{r}
#MOodule score

tonsil <- AddModuleScore(object = tonsil, features = c("CD68", "CD163", "CD14", "CSF1R"), name = "MacrophageList")
FeaturePlot(object = tonsil, features = "MacrophageList1")  + scale_colour_gradientn(colours = rev(brewer.pal(n = 9, name = "RdYlBu")))

tonsil <- AddModuleScore(object = tonsil, features = c("MS4A1", "CD79A", "CD79B", "CD19", "PAX5"), name = "BcellList")
FeaturePlot(object = tonsil, features = "BcellList1")  + scale_colour_gradientn(colours = rev(brewer.pal(n = 9, name = "RdYlBu")))

tonsil <- AddModuleScore(object = tonsil, features = c("CD3D", "CD3E", "UBASH3A", "CD2", "TRBC2"), name = "TcellList")
FeaturePlot(object = tonsil, features = "TcellList1")  + scale_colour_gradientn(colours = rev(brewer.pal(n = 9, name = "RdYlBu")))

```

